### ISSUE TITLE
Hello World example

### ISSUE THREAD

**Issue by newtack** [Agamennon/redux-tiny-router#1]
Between react-router (which looks like overkill and not well fitted for redux) and nothing (https://gist.github.com/HenrikJoreteg/530c1da6a5e0ff9bd9ad) this router looks very good. I may have missed it but I don't see any hello world example or any pointers. Could you please provide something, even if it is only a short description?

**Comment by Agamennon** [comment]
yup thats the idea, will hopefully  be done by monday with a full read-me and examples... also it will do universal apps like a champ

**Comment by Agamennon** [comment]
The first draft of the documentation is done, tell me if you have any problems, corrections or suggestions!
