### ISSUE TITLE
Getting error when using OPTION2 initialization

### ISSUE THREAD

**Issue by zkochan** [Agamennon/redux-tiny-router#11]
When using the OPTION2 initialization, described in the README.md, getting this JavaScript error:

```
Uncaught ReferenceError: __UNIVERSAL__ is not defined
```

Setting `window.__UNIVERSAL__ = false;` before initialization fixes the issue.

The error is happening in `reduxTinyRouter.js` at `window.__UNIVERSAL__ = __UNIVERSAL__ || false;`

**Comment by Agamennon** [comment]
@zkochan  Thanks for reporting, this issue will be gone on next version
