### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by patrick-jones** [Agamennon/redux-tiny-router#16]
package.json lists react ^0.13.3 as a dependency. It seems more appropriate to be a peer dependency, in any case.

**Comment by approots** [comment]
+1. Redux-tiny-router is including its own version of react. Makes for a large file size. Had to fork and rebuild without the react/redux dependencies.

**Comment by Agamennon** [comment]
Will be fixed, i will release a 0.13.3 version tag as peer dependency and a 0.14.4 version as soon as i am back in the country

**Comment by plandem** [comment]
is project dead?

**Comment by Agamennon** [comment]
no, there is a react 0.14 branch
