### ISSUE TITLE
Make use of the history library

### ISSUE THREAD

**Issue by gausie** [Agamennon/redux-tiny-router#20]
Aside from the great set of edge-cases it handles, using history in r-t-r would allow the use of extensions such as [redux-history-transitions](https://github.com/johanneslumpe/redux-history-transitions).

**Comment by gausie** [comment]
Haha I just looked at your discussion with @gaearon. Can't say I agree with him, but it does seem sensible to try to get the simplicity of r-t-r using history as a library.

**Comment by Agamennon** [comment]
@gausie (sorry for the delayed response) history is awesome, but it fixes a problem we don't have, by sticking with ie10+  and only using pushState r-t-r  can eschew a hole class of problems.
