### ISSUE TITLE
Vitality of the project ?

### ISSUE THREAD

**Issue by nihaux** [Agamennon/redux-tiny-router#26]
Hello @Agamennon 

first I'd like to thank you for this library, love the philosophy. I was going to write something similar myself when I stubbled uppon your code :)
That said, as I am starting a new project in my company, I am a little worried to see that pull request from months ago are still to be merged.
So I guess my question is, are you still maintaining this project ?
I'll be glad to help if needed.

**Comment by plandem** [comment]
you can also check this one:
https://github.com/callum/redux-routing
