### ISSUE TITLE
Remove rtr- prefix

### ISSUE THREAD

**Issue by srph** [Agamennon/redux-tiny-router#3]
I find it weird. Is there a good reason we have this?

By the way, thanks for your good work! :smile:

**Comment by alkhe** [comment]
I mentioned it [here](https://github.com/rackt/redux/issues/656) yesterday.

**Comment by Agamennon** [comment]
The prefixing is there to avoid collision in case of user bindActionCreators but i am not sure if its necessary, lets leave it like this for a day or two, if no one makes a case in favor of  it, it will be gone.

**Comment by Agamennon** [comment]
humm... next version this prefixing will die, last chance!

**Comment by srph** [comment]
It's going away? Nice!

**Comment by Agamennon** [comment]
@srph @edge , new version is up with many changes, docs are redone, and no more prefixing!

**Comment by srph** [comment]
Awesome. Thanks!
