### ISSUE TITLE
URL Params support?

### ISSUE THREAD

**Issue by aphillipo** [Agamennon/redux-tiny-router#4]
For example I like the way flask does it and forces a type:

```
/project/edit/<int:project_id>/
```

Additionally I'd say then you need a way to generate a URL as well... 

I'd love it if there was a global way to add the trailing slash or not as well.

But this currently looks very clean and reduxy ;-)  React Router is very overbearing and I'm not sure they have got everything right with their recent 1.0 API changes. Well played.

**Comment by Agamennon** [comment]
Thanks, i think that can be done, let me look more into it, also i will push a new version today or  tomorrow, with some changes, more docs and a boilerplate.

**Comment by Agamennon** [comment]
The new version is up, with an example app and  more documentation, in there you will find in "the utils" section there is a prototype idea for you to comment on.

**Comment by Agamennon** [comment]
@aphillipo another version is now up, with route definitions, it does not have type information, but its flexible, also you can use trailing slashes as it's not relevant in the current implementation just make your calls to navigatoTo with the trailing slash, you could even force it on your middleware just by adding a trailing slash to action.router.url in the ROUTER_NAVIGATION action if it's missing one. 
I will close this issue, if you feel there is something missing on URL params support i will reopen this one.
