### ISSUE TITLE
__UNIVERSAL__ && __CLIENT__ undefined

### ISSUE THREAD

**Issue by quazzie** [Agamennon/redux-tiny-router#5]
Getting __UNIVERSAL__ and __CLIENT__ undefined.

**Comment by Agamennon** [comment]
will push a new version later today, it will have an boilerplate, and more documentation, please try this for now , place this right at the start of your script, before you createStore

```
 window.__UNIVERSAL__ = false;
 window.__CLIENT__ = true;
```

**Comment by Agamennon** [comment]
A new version is now in effect with an example app too, take a look at the new documentation and the example,  i have also in this update resolved this issue, please re-open if you are still having problems
