### ISSUE TITLE
Redirecting after submitting a form

### ISSUE THREAD

**Issue by emmenko** [Agamennon/redux-tiny-router#7]
Hey,

your library sounds interesting!

I have one question though which apparently is quite unclear how to solve it with redux + router.

So let's say I'm on a page where I have a form. I fill up the form and I submit it. After the submit, if successful, I want to redirect to another page otherwise show an error message on the form page itself.
This is a quite common use case but I haven't figure it out how to properly redirect.

The flow looks like this:
- render component page with form
- fill up form
- submit form
- execute action
- make api request
- dispatch action
- update reducer state
- app re-renders

Before the last step I should know if I need to redirect or re-render and show an error message. But how would you do it? The reducer simply returns the state and the component needs to check for something to make a decision (e.g.: redirect or not). I could set into the state something like `shouldRedirect: true` so the component knows it has to redirect but this is not nice.

Ideally I want to say: given that action I want to transition to somewhere.

What are your thoughts? Thanks!

**Comment by Agamennon** [comment]
basically what you do is on the resolution of the api request, the "on success" you `dispatch(routerActions.navigateTo('/somepath')`  to redirect the user, if you set up your app to look at the router state, the app will render the correct component 

I just pushed a new version with more documentation and a example app, it has some flow there similar to what you want, take a look and if you have any more questions just ask!

**Comment by Agamennon** [comment]
@emmenko well there is yet another version up, i have rewritten the documentation, and added route definitions, please send in your suggestions.

**Comment by emmenko** [comment]
@Agamennon thanks! I'll have a look. But your suggestion already helped me :)
